# Generated by Django 4.2 on 2025-08-05 05:14

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0005_shelf_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shelf',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shelf',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shelf',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
